/* Generated by scripts/export_c_params.py from configs/pipeline.toml and
 * models/v1.0_robust.json (frozen v1.0); do not edit. */
#ifndef VGATE_PARAMS_H
#define VGATE_PARAMS_H

#define VGATE_FS 360
#define VGATE_PT_N_SECTIONS 2
#define VGATE_PT_N_DER 5
#define VGATE_PT_N_MWI 54
#define VGATE_PT_BP_DELAY 15
#define VGATE_PT_REFRACTORY 72
#define VGATE_PT_T_WAVE 130
#define VGATE_PT_N_LEARN 720
#define VGATE_PT_N_HIST 1080
#define VGATE_PT_CHUNK 3600
#define VGATE_BP_N_SECTIONS 2
#define VGATE_RR_HISTORY 10
#define VGATE_R_SEARCH 18
#define VGATE_S_SEARCH 29
#define VGATE_W0 (-90)
#define VGATE_W1 162
#define VGATE_SEG_LEN 253
#define VGATE_WAVELET_LEVEL 5
#define VGATE_WAVELET_LEN 8
#define VGATE_RR_CAP_SAMPLES 720
#define VGATE_TIMEOUT_SAMPLES 720
#define VGATE_WINDOW 3600
#define VGATE_MIN_BEATS 3
#define VGATE_SKIP_FIRST_WINDOW 1
#define VGATE_N_FEATURES 14
#define VGATE_RR_CAP 2.0
#define VGATE_THRESHOLD 0.0

/* Pan-Tompkins front end (float64, as the Python reference). */
extern const double vgate_pt_sos[VGATE_PT_N_SECTIONS][6];
extern const double vgate_pt_zi[VGATE_PT_N_SECTIONS][2];
extern const double vgate_pt_der[VGATE_PT_N_DER];
extern const double vgate_pt_mwi_b;
/* Classifier band-pass (float32). */
extern const float vgate_bp_sos[VGATE_BP_N_SECTIONS][6];
extern const float vgate_bp_zi[VGATE_BP_N_SECTIONS][2];
/* db4 decomposition filters. */
extern const double vgate_dec_lo[VGATE_WAVELET_LEN];
extern const double vgate_dec_hi[VGATE_WAVELET_LEN];
/* Robust SVM: decision = ((f - mean) / scale) . coef + intercept. */
extern const double vgate_svm_mean[VGATE_N_FEATURES];
extern const double vgate_svm_scale[VGATE_N_FEATURES];
extern const double vgate_svm_coef[VGATE_N_FEATURES];
extern const double vgate_svm_intercept;

#endif
