"""Export Python reference vectors for the C core tests (c/tests/vectors/).

  python scripts/export_c_vectors.py

Band-pass: 10 s of DS1-train record 119 (MLII, mV) through dsp.filters.bandpass
(float32 SOS, steady-state start). The C test must match within 1e-4 mV.
"""

from __future__ import annotations

import numpy as np
from scipy import signal

from vgate import config
from vgate.data import mitdb
from vgate.dsp.filters import bandpass, design_bandpass

OUT = config.ROOT / "c" / "tests" / "vectors" / "bandpass_119.h"
RECORD, N = 119, 3600


def _f(v: float) -> str:
    """C float literal, e.g. 1 -> 1.0f."""
    s = f"{v:.9g}"
    return (s if any(c in s for c in ".en") else s + ".0") + "f"


def _array(name: str, a: np.ndarray) -> str:
    vals = ",\n".join(
        "    " + ", ".join(_f(v) for v in a[i : i + 6]) for i in range(0, len(a), 6)
    )
    return f"static const float {name}[{len(a)}] = {{\n{vals}\n}};\n"


def main() -> None:
    x = mitdb.load_record(RECORD).signal[:N].astype(np.float32)
    sos = design_bandpass()
    zi = signal.sosfilt_zi(sos).astype(np.float32)
    y = bandpass(x, sos)
    parts = [
        f"/* Generated by scripts/export_c_vectors.py: record {RECORD}, first {N} samples. */",
        "#ifndef VGATE_VECTORS_BANDPASS_119_H",
        "#define VGATE_VECTORS_BANDPASS_119_H",
        f"#define BP_N_SECTIONS {len(sos)}",
        f"#define BP_N {N}",
        "static const float BP_SOS[BP_N_SECTIONS][6] = {"
        + ", ".join("{" + ", ".join(_f(v) for v in s) + "}" for s in sos) + "};",
        "static const float BP_ZI[BP_N_SECTIONS][2] = {"
        + ", ".join("{" + ", ".join(_f(v) for v in z) + "}" for z in zi) + "};",
        _array("BP_X", x),
        _array("BP_Y", y),
        "#endif",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(parts) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
