"""Export Python reference vectors for the C core tests (c/tests/vectors/).

  python scripts/export_c_vectors.py

Band-pass: five synthetic signals (impulse, step, 10 Hz sine, 0.2 Hz baseline sine,
white noise) and 5 s of DS1-train record 119 (MLII, mV), each 1800 samples, through
dsp.filters.bandpass (float32 SOS, steady-state start). The C test must match within
1e-4 mV.
"""

from __future__ import annotations

import numpy as np
from scipy import signal

from vgate import config
from vgate.data import mitdb
from vgate.dsp.filters import bandpass, design_bandpass

OUT = config.ROOT / "c" / "tests" / "vectors" / "bandpass_vectors.h"
RECORD, N, FS = 119, 1800, 360


def inputs() -> dict[str, np.ndarray]:
    t = np.arange(N) / FS
    impulse = np.zeros(N)
    impulse[100] = 1.0
    return {
        "impulse": impulse,
        "step": (np.arange(N) >= FS).astype(float),
        "sine_10hz": np.sin(2 * np.pi * 10 * t),
        "sine_0p2hz": np.sin(2 * np.pi * 0.2 * t),
        "white_noise": np.random.default_rng(0).normal(size=N),
        f"record_{RECORD}": mitdb.load_record(RECORD).signal[:N],
    }


def _f(v: float) -> str:
    """C float literal, e.g. 1 -> 1.0f."""
    s = f"{v:.9g}"
    return (s if any(c in s for c in ".en") else s + ".0") + "f"


def _rows(a: np.ndarray) -> str:
    return ",\n".join("    " + ", ".join(_f(v) for v in a[i : i + 6]) for i in range(0, len(a), 6))


def main() -> None:
    sos = design_bandpass()
    zi = signal.sosfilt_zi(sos).astype(np.float32)
    sets = {k: v.astype(np.float32) for k, v in inputs().items()}
    xs = ",\n".join("  {\n" + _rows(x) + "\n  }" for x in sets.values())
    ys = ",\n".join("  {\n" + _rows(bandpass(x, sos)) + "\n  }" for x in sets.values())
    parts = [
        "/* Generated by scripts/export_c_vectors.py; do not edit. */",
        "#ifndef VGATE_VECTORS_BANDPASS_H",
        "#define VGATE_VECTORS_BANDPASS_H",
        f"#define BP_N_SECTIONS {len(sos)}",
        f"#define BP_N_SETS {len(sets)}",
        f"#define BP_N {N}",
        "static const float BP_SOS[BP_N_SECTIONS][6] = {"
        + ", ".join("{" + ", ".join(_f(v) for v in s) + "}" for s in sos) + "};",
        "static const float BP_ZI[BP_N_SECTIONS][2] = {"
        + ", ".join("{" + ", ".join(_f(v) for v in z) + "}" for z in zi) + "};",
        "static const char *const BP_NAMES[BP_N_SETS] = {"
        + ", ".join(f'"{k}"' for k in sets) + "};",
        f"static const float BP_X[BP_N_SETS][BP_N] = {{\n{xs}\n}};",
        f"static const float BP_Y[BP_N_SETS][BP_N] = {{\n{ys}\n}};",
        "#endif",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(parts) + "\n")
    old = OUT.parent / "bandpass_119.h"
    if old.exists():
        old.unlink()
    print(f"wrote {OUT} ({len(sets)} sets x {N} samples)")


if __name__ == "__main__":
    main()
