"""Export the frozen v1.0 constants for the C core (c/include/vgate/params.h, c/src/params.c).

  python scripts/export_c_params.py

Everything the C pipeline needs that Python derives at run time: the Pan-Tompkins
and classifier filter designs (SciPy), sosfilt_zi, the band-pass group delay, the
db4 decomposition filters (PyWavelets), sample counts from configs/pipeline.toml
and the Robust SVM weights from models/v1.0_robust.json. Doubles are written with
17 significant digits and floats with 9, so every value round-trips exactly.
"""

from __future__ import annotations

import numpy as np
import pywt
from scipy import signal

from vgate import config, design
from vgate.detectors import pan_tompkins
from vgate.dsp.filters import design_bandpass
from vgate.features import FEATURE_NAMES

HEADER = config.ROOT / "c" / "include" / "vgate" / "params.h"
SOURCE = config.ROOT / "c" / "src" / "params.c"


def _d(v: float) -> str:
    s = repr(float(v))
    return s if any(c in s for c in ".en") else s + ".0"


def _f(v: float) -> str:
    s = f"{np.float32(v):.9g}"
    return (s if any(c in s for c in ".en") else s + ".0") + "f"


def _arr(vals, fmt) -> str:
    return "{" + ", ".join(fmt(v) for v in vals) + "}"


def main() -> None:
    cfg = config.pipeline()
    fs = cfg["fs"]
    fc, wc = cfg["features"], cfg["windowing"]
    det = pan_tompkins.PanTompkins(fs)
    if det.zi_der.size != len(det.der) - 1:
        raise ValueError("unexpected derivative filter")
    pt_zi = signal.sosfilt_zi(det.sos)
    bp_sos = design_bandpass(fs)
    bp_zi = signal.sosfilt_zi(bp_sos).astype(np.float32)
    w0, w1 = (round(v * fs / 1000) for v in fc["wavelet_span_ms"])
    wav = pywt.Wavelet(fc["wavelet"])
    w = design.robust_weights()
    chunk = pan_tompkins.detect_with_widths.__defaults__[1]

    defines = {
        "VGATE_FS": fs,
        "VGATE_PT_N_SECTIONS": len(det.sos),
        "VGATE_PT_N_DER": len(det.der),
        "VGATE_PT_N_MWI": det.n_mwi,
        "VGATE_PT_BP_DELAY": det.bp_delay,
        "VGATE_PT_REFRACTORY": det.refractory,
        "VGATE_PT_T_WAVE": det.t_wave,
        "VGATE_PT_N_LEARN": det.n_learn,
        "VGATE_PT_N_HIST": max(det.n_hist, det.n_learn),
        "VGATE_PT_CHUNK": chunk,
        "VGATE_BP_N_SECTIONS": len(bp_sos),
        "VGATE_RR_HISTORY": fc["rr_history"],
        "VGATE_R_SEARCH": round(fc["r_search_ms"] * fs / 1000),
        "VGATE_S_SEARCH": round(fc["s_search_ms"] * fs / 1000),
        "VGATE_W0": w0,
        "VGATE_W1": w1,
        "VGATE_SEG_LEN": w1 - w0 + 1,
        "VGATE_WAVELET_LEVEL": 5,
        "VGATE_WAVELET_LEN": wav.dec_len,
        "VGATE_RR_CAP_SAMPLES": round(wc["censored_rr_s"] * fs),
        "VGATE_TIMEOUT_SAMPLES": round(wc["decision_timeout_s"] * fs),
        "VGATE_WINDOW": cfg["window_s"] * fs,
        "VGATE_MIN_BEATS": wc["min_beats"],
        "VGATE_SKIP_FIRST_WINDOW": int(cfg["filter"]["skip_first_window"]),
        "VGATE_N_FEATURES": len(FEATURE_NAMES),
    }
    header = [
        "/* Generated by scripts/export_c_params.py from configs/pipeline.toml and",
        " * models/v1.0_robust.json (frozen v1.0); do not edit. */",
        "#ifndef VGATE_PARAMS_H",
        "#define VGATE_PARAMS_H",
        "",
        *(f"#define {k} {v if v >= 0 else f'({v})'}" for k, v in defines.items()),
        f"#define VGATE_RR_CAP {_d(wc['censored_rr_s'])}",
        f"#define VGATE_THRESHOLD {_d(design.THRESHOLD)}",
        "",
        "/* Pan-Tompkins front end (float64, as the Python reference). */",
        "extern const double vgate_pt_sos[VGATE_PT_N_SECTIONS][6];",
        "extern const double vgate_pt_zi[VGATE_PT_N_SECTIONS][2];",
        "extern const double vgate_pt_der[VGATE_PT_N_DER];",
        "extern const double vgate_pt_mwi_b;",
        "/* Classifier band-pass (float32). */",
        "extern const float vgate_bp_sos[VGATE_BP_N_SECTIONS][6];",
        "extern const float vgate_bp_zi[VGATE_BP_N_SECTIONS][2];",
        "/* db4 decomposition filters. */",
        "extern const double vgate_dec_lo[VGATE_WAVELET_LEN];",
        "extern const double vgate_dec_hi[VGATE_WAVELET_LEN];",
        "/* Robust SVM: decision = ((f - mean) / scale) . coef + intercept. */",
        "extern const double vgate_svm_mean[VGATE_N_FEATURES];",
        "extern const double vgate_svm_scale[VGATE_N_FEATURES];",
        "extern const double vgate_svm_coef[VGATE_N_FEATURES];",
        "extern const double vgate_svm_intercept;",
        "",
        "#endif",
    ]
    source = [
        "/* Generated by scripts/export_c_params.py; do not edit. */",
        '#include "vgate/params.h"',
        "",
        "const double vgate_pt_sos[VGATE_PT_N_SECTIONS][6] = "
        + _arr(det.sos, lambda s: _arr(s, _d)) + ";",
        "const double vgate_pt_zi[VGATE_PT_N_SECTIONS][2] = "
        + _arr(pt_zi, lambda s: _arr(s, _d)) + ";",
        f"const double vgate_pt_der[VGATE_PT_N_DER] = {_arr(det.der, _d)};",
        f"const double vgate_pt_mwi_b = {_d((np.ones(det.n_mwi) / det.n_mwi)[0])};",
        "",
        "const float vgate_bp_sos[VGATE_BP_N_SECTIONS][6] = "
        + _arr(bp_sos, lambda s: _arr(s, _f)) + ";",
        "const float vgate_bp_zi[VGATE_BP_N_SECTIONS][2] = "
        + _arr(bp_zi, lambda s: _arr(s, _f)) + ";",
        "",
        f"const double vgate_dec_lo[VGATE_WAVELET_LEN] = {_arr(wav.dec_lo, _d)};",
        f"const double vgate_dec_hi[VGATE_WAVELET_LEN] = {_arr(wav.dec_hi, _d)};",
        "",
        f"const double vgate_svm_mean[VGATE_N_FEATURES] = {_arr(w['mean'], _d)};",
        f"const double vgate_svm_scale[VGATE_N_FEATURES] = {_arr(w['scale'], _d)};",
        f"const double vgate_svm_coef[VGATE_N_FEATURES] = {_arr(w['coef'], _d)};",
        f"const double vgate_svm_intercept = {_d(w['intercept'])};",
    ]
    HEADER.write_text("\n".join(header) + "\n")
    SOURCE.write_text("\n".join(source) + "\n")
    print(f"wrote {HEADER.relative_to(config.ROOT)} and {SOURCE.relative_to(config.ROOT)}")


if __name__ == "__main__":
    main()
