"""Export Python reference vectors for the C core tests (c/tests/vectors/).

  python scripts/export_c_vectors.py

Band-pass: five synthetic signals (impulse, step, 10 Hz sine, 0.2 Hz baseline sine,
white noise) and 5 s of DS1-train record 119 (MLII, mV), each 1800 samples, through
dsp.filters.bandpass (float32 SOS, steady-state start). The C test must match within
1e-4 mV.

Pipeline: two 60 s excerpts -- DS1-train record 119 (clean) and record 208 mixed with
NSTDB em noise inside its 6 dB segment (schedule offset 0, train blocks) -- rounded
to MIT-BIH ADC counts (1/200 mV) so C and Python get bit-identical input, then run
through vgate.reference: R peaks, QRS widths, features, decision values and window
states for c/tests/test_pipeline.c.
"""

from __future__ import annotations

import numpy as np
from scipy import signal

from vgate import config
from vgate.data import mitdb
from vgate.dsp.filters import bandpass, design_bandpass
from vgate.features import FEATURE_NAMES
from vgate.pipeline import Copy, _noisy_signal
from vgate.reference import run as reference

OUT = config.ROOT / "c" / "tests" / "vectors" / "bandpass_vectors.h"
PIPE_OUT = OUT.parent / "pipeline_vectors.h"
RECORD, N, FS = 119, 1800, 360
GAIN, PIPE_S = 200.0, 60
STATES = {"insufficient": 0, "V suspected": 1, "no V": 2}


def inputs() -> dict[str, np.ndarray]:
    t = np.arange(N) / FS
    impulse = np.zeros(N)
    impulse[100] = 1.0
    return {
        "impulse": impulse,
        "step": (np.arange(N) >= FS).astype(float),
        "sine_10hz": np.sin(2 * np.pi * 10 * t),
        "sine_0p2hz": np.sin(2 * np.pi * 0.2 * t),
        "white_noise": np.random.default_rng(0).normal(size=N),
        f"record_{RECORD}": mitdb.load_record(RECORD).signal[:N],
    }


def _f(v: float) -> str:
    """C float literal, e.g. 1 -> 1.0f."""
    s = f"{v:.9g}"
    return (s if any(c in s for c in ".en") else s + ".0") + "f"


def _rows(a: np.ndarray) -> str:
    return ",\n".join("    " + ", ".join(_f(v) for v in a[i : i + 6]) for i in range(0, len(a), 6))


def _d(v: float) -> str:
    """C double literal that round-trips exactly."""
    s = repr(float(v))
    return s if any(c in s for c in ".en") else s + ".0"


def _block(rows: list[str]) -> str:
    return "{\n" + ",\n".join(rows) + "\n}"


def pipeline_inputs() -> dict[str, np.ndarray]:
    """ADC-count excerpts; raw mV = counts / GAIN on both sides."""
    clean = mitdb.load_record(RECORD).signal[: PIPE_S * FS]
    c = Copy(208, "train", "em", 0)
    noisy, _ = _noisy_signal(c, mitdb.load_record(c.record))
    a = round(13.25 * 60 * FS)
    return {
        f"{RECORD}_clean": np.round(clean * GAIN).astype(np.int16),
        "208_em_6dB": np.round(noisy[a : a + PIPE_S * FS] * GAIN).astype(np.int16),
    }


def export_pipeline() -> None:
    sets = pipeline_inputs()
    refs = [reference(x / GAIN) for x in sets.values()]
    nb = max(len(r["det"]) for r in refs)
    nw = max(len(r["states"]) for r in refs)
    nf = len(FEATURE_NAMES)

    def padded(vals: list[str], n: int, pad: str) -> str:
        return "  {" + ", ".join(vals + [pad] * (n - len(vals))) + "}"

    def beats(key: str, fmt) -> str:
        return _block([padded([fmt(v) for v in r[key]], nb, fmt(0)) for r in refs])

    feats = _block([
        padded(["{" + ", ".join(_d(v) for v in row) + "}" for row in r["features"]], nb,
               "{" + ", ".join(["0.0"] * nf) + "}")
        for r in refs
    ])  # fmt: skip
    states = _block([padded([str(STATES[s]) for s in r["states"]], nw, "0") for r in refs])
    xs = _block([
        "  {\n" + ",\n".join("    " + ", ".join(str(int(v)) for v in x[i : i + 16])
                             for i in range(0, len(x), 16)) + "\n  }"
        for x in sets.values()
    ])  # fmt: skip
    parts = [
        "/* Generated by scripts/export_c_vectors.py; do not edit. */",
        "#ifndef VGATE_VECTORS_PIPELINE_H",
        "#define VGATE_VECTORS_PIPELINE_H",
        f"#define PV_N_SETS {len(sets)}",
        f"#define PV_N {PIPE_S * FS}",
        f"#define PV_GAIN {_d(GAIN)}",
        f"#define PV_MAX_BEATS {nb}",
        f"#define PV_MAX_WINDOWS {nw}",
        "static const char *const PV_NAMES[PV_N_SETS] = {"
        + ", ".join(f'"{k}"' for k in sets) + "};",
        "/* raw mV = PV_X / PV_GAIN */",
        f"static const short PV_X[PV_N_SETS][PV_N] = {xs};",
        "static const int PV_N_BEATS[PV_N_SETS] = {"
        + ", ".join(str(len(r["det"])) for r in refs) + "};",
        "static const int PV_R[PV_N_SETS][PV_MAX_BEATS] = " + beats("det", str) + ";",
        "static const double PV_WIDTH[PV_N_SETS][PV_MAX_BEATS] = " + beats("width", _d) + ";",
        f"static const double PV_FEATURES[PV_N_SETS][PV_MAX_BEATS][{nf}] = {feats};",
        "static const double PV_DECISION[PV_N_SETS][PV_MAX_BEATS] = "
        + beats("decision", _d) + ";",
        "static const int PV_N_WINDOWS[PV_N_SETS] = {"
        + ", ".join(str(len(r["states"])) for r in refs) + "};",
        "/* 0 insufficient, 1 V suspected, 2 no V (vgate_state_t) */",
        f"static const int PV_STATE[PV_N_SETS][PV_MAX_WINDOWS] = {states};",
        "#endif",
    ]
    PIPE_OUT.write_text("\n".join(parts) + "\n")
    print(f"wrote {PIPE_OUT} (" + "; ".join(
        f"{k}: {len(r['det'])} beats, {int((r['decision'] > 0).sum())} V calls, "
        f"{len(r['states'])} windows" for k, r in zip(sets, refs, strict=True)) + ")")  # fmt: skip


def main() -> None:
    sos = design_bandpass()
    zi = signal.sosfilt_zi(sos).astype(np.float32)
    sets = {k: v.astype(np.float32) for k, v in inputs().items()}
    xs = ",\n".join("  {\n" + _rows(x) + "\n  }" for x in sets.values())
    ys = ",\n".join("  {\n" + _rows(bandpass(x, sos)) + "\n  }" for x in sets.values())
    parts = [
        "/* Generated by scripts/export_c_vectors.py; do not edit. */",
        "#ifndef VGATE_VECTORS_BANDPASS_H",
        "#define VGATE_VECTORS_BANDPASS_H",
        f"#define BP_N_SECTIONS {len(sos)}",
        f"#define BP_N_SETS {len(sets)}",
        f"#define BP_N {N}",
        "static const float BP_SOS[BP_N_SECTIONS][6] = {"
        + ", ".join("{" + ", ".join(_f(v) for v in s) + "}" for s in sos) + "};",
        "static const float BP_ZI[BP_N_SECTIONS][2] = {"
        + ", ".join("{" + ", ".join(_f(v) for v in z) + "}" for z in zi) + "};",
        "static const char *const BP_NAMES[BP_N_SETS] = {"
        + ", ".join(f'"{k}"' for k in sets) + "};",
        f"static const float BP_X[BP_N_SETS][BP_N] = {{\n{xs}\n}};",
        f"static const float BP_Y[BP_N_SETS][BP_N] = {{\n{ys}\n}};",
        "#endif",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(parts) + "\n")
    old = OUT.parent / "bandpass_119.h"
    if old.exists():
        old.unlink()
    print(f"wrote {OUT} ({len(sets)} sets x {N} samples)")
    export_pipeline()


if __name__ == "__main__":
    main()
